// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package tejas.cloud.assignment1.proto;

public final class ProductsProtoc {
  private ProductsProtoc() {}
  public static void registerAllExtensions(
      com.github.os72.protobuf241.ExtensionRegistry registry) {
  }
  public interface GetProductOrBuilder
      extends com.github.os72.protobuf241.MessageOrBuilder {
    
    // required int32 requestID = 1;
    boolean hasRequestID();
    int getRequestID();
    
    // required int32 accountID = 2;
    boolean hasAccountID();
    int getAccountID();
    
    // required int32 productNumber = 3;
    boolean hasProductNumber();
    int getProductNumber();
    
    // required string productCategory = 4;
    boolean hasProductCategory();
    String getProductCategory();
    
    // required int32 quantity = 5;
    boolean hasQuantity();
    int getQuantity();
  }
  public static final class GetProduct extends
      com.github.os72.protobuf241.GeneratedMessage
      implements GetProductOrBuilder {
    // Use GetProduct.newBuilder() to construct.
    private GetProduct(Builder builder) {
      super(builder);
    }
    private GetProduct(boolean noInit) {}
    
    private static final GetProduct defaultInstance;
    public static GetProduct getDefaultInstance() {
      return defaultInstance;
    }
    
    public GetProduct getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.github.os72.protobuf241.Descriptors.Descriptor
        getDescriptor() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
    }
    
    protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 requestID = 1;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private int requestID_;
    public boolean hasRequestID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getRequestID() {
      return requestID_;
    }
    
    // required int32 accountID = 2;
    public static final int ACCOUNTID_FIELD_NUMBER = 2;
    private int accountID_;
    public boolean hasAccountID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getAccountID() {
      return accountID_;
    }
    
    // required int32 productNumber = 3;
    public static final int PRODUCTNUMBER_FIELD_NUMBER = 3;
    private int productNumber_;
    public boolean hasProductNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getProductNumber() {
      return productNumber_;
    }
    
    // required string productCategory = 4;
    public static final int PRODUCTCATEGORY_FIELD_NUMBER = 4;
    private java.lang.Object productCategory_;
    public boolean hasProductCategory() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public String getProductCategory() {
      java.lang.Object ref = productCategory_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.github.os72.protobuf241.ByteString bs = 
            (com.github.os72.protobuf241.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.github.os72.protobuf241.Internal.isValidUtf8(bs)) {
          productCategory_ = s;
        }
        return s;
      }
    }
    private com.github.os72.protobuf241.ByteString getProductCategoryBytes() {
      java.lang.Object ref = productCategory_;
      if (ref instanceof String) {
        com.github.os72.protobuf241.ByteString b = 
            com.github.os72.protobuf241.ByteString.copyFromUtf8((String) ref);
        productCategory_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf241.ByteString) ref;
      }
    }
    
    // required int32 quantity = 5;
    public static final int QUANTITY_FIELD_NUMBER = 5;
    private int quantity_;
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public int getQuantity() {
      return quantity_;
    }
    
    private void initFields() {
      requestID_ = 0;
      accountID_ = 0;
      productNumber_ = 0;
      productCategory_ = "";
      quantity_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasRequestID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProductNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProductCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.github.os72.protobuf241.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, requestID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, accountID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, productNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getProductCategoryBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, quantity_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeInt32Size(1, requestID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeInt32Size(2, accountID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeInt32Size(3, productNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeBytesSize(4, getProductCategoryBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeInt32Size(5, quantity_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.github.os72.protobuf241.ByteString data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.github.os72.protobuf241.ByteString data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(byte[] data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        byte[] data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseDelimitedFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.github.os72.protobuf241.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.github.os72.protobuf241.CodedInputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.github.os72.protobuf241.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.github.os72.protobuf241.GeneratedMessage.Builder<Builder>
       implements tejas.cloud.assignment1.proto.ProductsProtoc.GetProductOrBuilder {
      public static final com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptor() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
      }
      
      protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable;
      }
      
      // Construct using tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.github.os72.protobuf241.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        requestID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        productNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        productCategory_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptorForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.getDescriptor();
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct getDefaultInstanceForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.getDefaultInstance();
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct build() {
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct buildParsed()
          throws com.github.os72.protobuf241.InvalidProtocolBufferException {
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct buildPartial() {
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct result = new tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestID_ = requestID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountID_ = accountID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.productNumber_ = productNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.productCategory_ = productCategory_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.quantity_ = quantity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.github.os72.protobuf241.Message other) {
        if (other instanceof tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct) {
          return mergeFrom((tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct other) {
        if (other == tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.getDefaultInstance()) return this;
        if (other.hasRequestID()) {
          setRequestID(other.getRequestID());
        }
        if (other.hasAccountID()) {
          setAccountID(other.getAccountID());
        }
        if (other.hasProductNumber()) {
          setProductNumber(other.getProductNumber());
        }
        if (other.hasProductCategory()) {
          setProductCategory(other.getProductCategory());
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasRequestID()) {
          
          return false;
        }
        if (!hasAccountID()) {
          
          return false;
        }
        if (!hasProductNumber()) {
          
          return false;
        }
        if (!hasProductCategory()) {
          
          return false;
        }
        if (!hasQuantity()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.github.os72.protobuf241.CodedInputStream input,
          com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.os72.protobuf241.UnknownFieldSet.Builder unknownFields =
          com.github.os72.protobuf241.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              productNumber_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              productCategory_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              quantity_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 requestID = 1;
      private int requestID_ ;
      public boolean hasRequestID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getRequestID() {
        return requestID_;
      }
      public Builder setRequestID(int value) {
        bitField0_ |= 0x00000001;
        requestID_ = value;
        onChanged();
        return this;
      }
      public Builder clearRequestID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestID_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 accountID = 2;
      private int accountID_ ;
      public boolean hasAccountID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getAccountID() {
        return accountID_;
      }
      public Builder setAccountID(int value) {
        bitField0_ |= 0x00000002;
        accountID_ = value;
        onChanged();
        return this;
      }
      public Builder clearAccountID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountID_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 productNumber = 3;
      private int productNumber_ ;
      public boolean hasProductNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getProductNumber() {
        return productNumber_;
      }
      public Builder setProductNumber(int value) {
        bitField0_ |= 0x00000004;
        productNumber_ = value;
        onChanged();
        return this;
      }
      public Builder clearProductNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        productNumber_ = 0;
        onChanged();
        return this;
      }
      
      // required string productCategory = 4;
      private java.lang.Object productCategory_ = "";
      public boolean hasProductCategory() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public String getProductCategory() {
        java.lang.Object ref = productCategory_;
        if (!(ref instanceof String)) {
          String s = ((com.github.os72.protobuf241.ByteString) ref).toStringUtf8();
          productCategory_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setProductCategory(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        productCategory_ = value;
        onChanged();
        return this;
      }
      public Builder clearProductCategory() {
        bitField0_ = (bitField0_ & ~0x00000008);
        productCategory_ = getDefaultInstance().getProductCategory();
        onChanged();
        return this;
      }
      void setProductCategory(com.github.os72.protobuf241.ByteString value) {
        bitField0_ |= 0x00000008;
        productCategory_ = value;
        onChanged();
      }
      
      // required int32 quantity = 5;
      private int quantity_ ;
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public int getQuantity() {
        return quantity_;
      }
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000010;
        quantity_ = value;
        onChanged();
        return this;
      }
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        quantity_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tejas.cloud.assignment1.proto.GetProduct)
    }
    
    static {
      defaultInstance = new GetProduct(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tejas.cloud.assignment1.proto.GetProduct)
  }
  
  public interface ProductSuccessOrBuilder
      extends com.github.os72.protobuf241.MessageOrBuilder {
    
    // required int32 unitPrice = 2;
    boolean hasUnitPrice();
    int getUnitPrice();
    
    // required int32 priceValidationPeriod = 3;
    boolean hasPriceValidationPeriod();
    int getPriceValidationPeriod();
  }
  public static final class ProductSuccess extends
      com.github.os72.protobuf241.GeneratedMessage
      implements ProductSuccessOrBuilder {
    // Use ProductSuccess.newBuilder() to construct.
    private ProductSuccess(Builder builder) {
      super(builder);
    }
    private ProductSuccess(boolean noInit) {}
    
    private static final ProductSuccess defaultInstance;
    public static ProductSuccess getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductSuccess getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.github.os72.protobuf241.Descriptors.Descriptor
        getDescriptor() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
    }
    
    protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 unitPrice = 2;
    public static final int UNITPRICE_FIELD_NUMBER = 2;
    private int unitPrice_;
    public boolean hasUnitPrice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getUnitPrice() {
      return unitPrice_;
    }
    
    // required int32 priceValidationPeriod = 3;
    public static final int PRICEVALIDATIONPERIOD_FIELD_NUMBER = 3;
    private int priceValidationPeriod_;
    public boolean hasPriceValidationPeriod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getPriceValidationPeriod() {
      return priceValidationPeriod_;
    }
    
    private void initFields() {
      unitPrice_ = 0;
      priceValidationPeriod_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasUnitPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriceValidationPeriod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.github.os72.protobuf241.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, unitPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, priceValidationPeriod_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeInt32Size(2, unitPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeInt32Size(3, priceValidationPeriod_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.github.os72.protobuf241.ByteString data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.github.os72.protobuf241.ByteString data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(byte[] data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        byte[] data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseDelimitedFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.github.os72.protobuf241.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.github.os72.protobuf241.CodedInputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.github.os72.protobuf241.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.github.os72.protobuf241.GeneratedMessage.Builder<Builder>
       implements tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccessOrBuilder {
      public static final com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptor() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
      }
      
      protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable;
      }
      
      // Construct using tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.github.os72.protobuf241.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        unitPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        priceValidationPeriod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptorForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.getDescriptor();
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess getDefaultInstanceForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.getDefaultInstance();
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess build() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess buildParsed()
          throws com.github.os72.protobuf241.InvalidProtocolBufferException {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess buildPartial() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess result = new tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unitPrice_ = unitPrice_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.priceValidationPeriod_ = priceValidationPeriod_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.github.os72.protobuf241.Message other) {
        if (other instanceof tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess) {
          return mergeFrom((tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess other) {
        if (other == tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.getDefaultInstance()) return this;
        if (other.hasUnitPrice()) {
          setUnitPrice(other.getUnitPrice());
        }
        if (other.hasPriceValidationPeriod()) {
          setPriceValidationPeriod(other.getPriceValidationPeriod());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasUnitPrice()) {
          
          return false;
        }
        if (!hasPriceValidationPeriod()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.github.os72.protobuf241.CodedInputStream input,
          com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.os72.protobuf241.UnknownFieldSet.Builder unknownFields =
          com.github.os72.protobuf241.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              unitPrice_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              priceValidationPeriod_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 unitPrice = 2;
      private int unitPrice_ ;
      public boolean hasUnitPrice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getUnitPrice() {
        return unitPrice_;
      }
      public Builder setUnitPrice(int value) {
        bitField0_ |= 0x00000001;
        unitPrice_ = value;
        onChanged();
        return this;
      }
      public Builder clearUnitPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unitPrice_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 priceValidationPeriod = 3;
      private int priceValidationPeriod_ ;
      public boolean hasPriceValidationPeriod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getPriceValidationPeriod() {
        return priceValidationPeriod_;
      }
      public Builder setPriceValidationPeriod(int value) {
        bitField0_ |= 0x00000002;
        priceValidationPeriod_ = value;
        onChanged();
        return this;
      }
      public Builder clearPriceValidationPeriod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        priceValidationPeriod_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:tejas.cloud.assignment1.proto.ProductSuccess)
    }
    
    static {
      defaultInstance = new ProductSuccess(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tejas.cloud.assignment1.proto.ProductSuccess)
  }
  
  public interface ProductErrorOrBuilder
      extends com.github.os72.protobuf241.MessageOrBuilder {
    
    // required bool error = 1;
    boolean hasError();
    boolean getError();
    
    // required string errorMessage = 2;
    boolean hasErrorMessage();
    String getErrorMessage();
  }
  public static final class ProductError extends
      com.github.os72.protobuf241.GeneratedMessage
      implements ProductErrorOrBuilder {
    // Use ProductError.newBuilder() to construct.
    private ProductError(Builder builder) {
      super(builder);
    }
    private ProductError(boolean noInit) {}
    
    private static final ProductError defaultInstance;
    public static ProductError getDefaultInstance() {
      return defaultInstance;
    }
    
    public ProductError getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.github.os72.protobuf241.Descriptors.Descriptor
        getDescriptor() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
    }
    
    protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required bool error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private boolean error_;
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getError() {
      return error_;
    }
    
    // required string errorMessage = 2;
    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private java.lang.Object errorMessage_;
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.github.os72.protobuf241.ByteString bs = 
            (com.github.os72.protobuf241.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.github.os72.protobuf241.Internal.isValidUtf8(bs)) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    private com.github.os72.protobuf241.ByteString getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof String) {
        com.github.os72.protobuf241.ByteString b = 
            com.github.os72.protobuf241.ByteString.copyFromUtf8((String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.github.os72.protobuf241.ByteString) ref;
      }
    }
    
    private void initFields() {
      error_ = false;
      errorMessage_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.github.os72.protobuf241.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getErrorMessageBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeBoolSize(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.github.os72.protobuf241.CodedOutputStream
          .computeBytesSize(2, getErrorMessageBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.github.os72.protobuf241.ByteString data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.github.os72.protobuf241.ByteString data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(byte[] data)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        byte[] data,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws com.github.os72.protobuf241.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseDelimitedFrom(
        java.io.InputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.github.os72.protobuf241.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.github.os72.protobuf241.CodedInputStream input,
        com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(tejas.cloud.assignment1.proto.ProductsProtoc.ProductError prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.github.os72.protobuf241.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.github.os72.protobuf241.GeneratedMessage.Builder<Builder>
       implements tejas.cloud.assignment1.proto.ProductsProtoc.ProductErrorOrBuilder {
      public static final com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptor() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
      }
      
      protected com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable;
      }
      
      // Construct using tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.github.os72.protobuf241.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        error_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.github.os72.protobuf241.Descriptors.Descriptor
          getDescriptorForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.getDescriptor();
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError getDefaultInstanceForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.getDefaultInstance();
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError build() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private tejas.cloud.assignment1.proto.ProductsProtoc.ProductError buildParsed()
          throws com.github.os72.protobuf241.InvalidProtocolBufferException {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError buildPartial() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductError result = new tejas.cloud.assignment1.proto.ProductsProtoc.ProductError(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.github.os72.protobuf241.Message other) {
        if (other instanceof tejas.cloud.assignment1.proto.ProductsProtoc.ProductError) {
          return mergeFrom((tejas.cloud.assignment1.proto.ProductsProtoc.ProductError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(tejas.cloud.assignment1.proto.ProductsProtoc.ProductError other) {
        if (other == tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasErrorMessage()) {
          setErrorMessage(other.getErrorMessage());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasError()) {
          
          return false;
        }
        if (!hasErrorMessage()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.github.os72.protobuf241.CodedInputStream input,
          com.github.os72.protobuf241.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.os72.protobuf241.UnknownFieldSet.Builder unknownFields =
          com.github.os72.protobuf241.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              error_ = input.readBool();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              errorMessage_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required bool error = 1;
      private boolean error_ ;
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public boolean getError() {
        return error_;
      }
      public Builder setError(boolean value) {
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = false;
        onChanged();
        return this;
      }
      
      // required string errorMessage = 2;
      private java.lang.Object errorMessage_ = "";
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof String)) {
          String s = ((com.github.os72.protobuf241.ByteString) ref).toStringUtf8();
          errorMessage_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setErrorMessage(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      void setErrorMessage(com.github.os72.protobuf241.ByteString value) {
        bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:tejas.cloud.assignment1.proto.ProductError)
    }
    
    static {
      defaultInstance = new ProductError(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:tejas.cloud.assignment1.proto.ProductError)
  }
  
  private static com.github.os72.protobuf241.Descriptors.Descriptor
    internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
  private static
    com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
      internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable;
  private static com.github.os72.protobuf241.Descriptors.Descriptor
    internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
  private static
    com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
      internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable;
  private static com.github.os72.protobuf241.Descriptors.Descriptor
    internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
  private static
    com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable
      internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable;
  
  public static com.github.os72.protobuf241.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.github.os72.protobuf241.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protobuf.proto\022\035tejas.cloud.assignment" +
      "1.proto\"t\n\nGetProduct\022\021\n\trequestID\030\001 \002(\005" +
      "\022\021\n\taccountID\030\002 \002(\005\022\025\n\rproductNumber\030\003 \002" +
      "(\005\022\027\n\017productCategory\030\004 \002(\t\022\020\n\010quantity\030" +
      "\005 \002(\005\"B\n\016ProductSuccess\022\021\n\tunitPrice\030\002 \002" +
      "(\005\022\035\n\025priceValidationPeriod\030\003 \002(\005\"3\n\014Pro" +
      "ductError\022\r\n\005error\030\001 \002(\010\022\024\n\014errorMessage" +
      "\030\002 \002(\tB/\n\035tejas.cloud.assignment1.protoB" +
      "\016ProductsProtoc"
    };
    com.github.os72.protobuf241.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.github.os72.protobuf241.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.github.os72.protobuf241.ExtensionRegistry assignDescriptors(
            com.github.os72.protobuf241.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable = new
            com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable(
              internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor,
              new java.lang.String[] { "RequestID", "AccountID", "ProductNumber", "ProductCategory", "Quantity", },
              tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.class,
              tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.Builder.class);
          internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable = new
            com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable(
              internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor,
              new java.lang.String[] { "UnitPrice", "PriceValidationPeriod", },
              tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.class,
              tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.Builder.class);
          internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable = new
            com.github.os72.protobuf241.GeneratedMessage.FieldAccessorTable(
              internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor,
              new java.lang.String[] { "Error", "ErrorMessage", },
              tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.class,
              tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.Builder.class);
          return null;
        }
      };
    com.github.os72.protobuf241.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.github.os72.protobuf241.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
