// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf.proto

package tejas.cloud.assignment1.proto;

public final class ProductsProtoc {
  private ProductsProtoc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetProductOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tejas.cloud.assignment1.proto.GetProduct)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 requestID = 1;</code>
     */
    boolean hasRequestID();
    /**
     * <code>required int32 requestID = 1;</code>
     */
    int getRequestID();

    /**
     * <code>required int32 accountID = 2;</code>
     */
    boolean hasAccountID();
    /**
     * <code>required int32 accountID = 2;</code>
     */
    int getAccountID();

    /**
     * <code>required int32 productNumber = 3;</code>
     */
    boolean hasProductNumber();
    /**
     * <code>required int32 productNumber = 3;</code>
     */
    int getProductNumber();

    /**
     * <code>required string productCategory = 4;</code>
     */
    boolean hasProductCategory();
    /**
     * <code>required string productCategory = 4;</code>
     */
    java.lang.String getProductCategory();
    /**
     * <code>required string productCategory = 4;</code>
     */
    com.google.protobuf.ByteString
        getProductCategoryBytes();

    /**
     * <code>required int32 quantity = 5;</code>
     */
    boolean hasQuantity();
    /**
     * <code>required int32 quantity = 5;</code>
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code tejas.cloud.assignment1.proto.GetProduct}
   */
  public  static final class GetProduct extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tejas.cloud.assignment1.proto.GetProduct)
      GetProductOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GetProduct.newBuilder() to construct.
    private GetProduct(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetProduct() {
      requestID_ = 0;
      accountID_ = 0;
      productNumber_ = 0;
      productCategory_ = "";
      quantity_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GetProduct(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              requestID_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              accountID_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              productNumber_ = input.readInt32();
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              productCategory_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              quantity_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.class, tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTID_FIELD_NUMBER = 1;
    private int requestID_;
    /**
     * <code>required int32 requestID = 1;</code>
     */
    public boolean hasRequestID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 requestID = 1;</code>
     */
    public int getRequestID() {
      return requestID_;
    }

    public static final int ACCOUNTID_FIELD_NUMBER = 2;
    private int accountID_;
    /**
     * <code>required int32 accountID = 2;</code>
     */
    public boolean hasAccountID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 accountID = 2;</code>
     */
    public int getAccountID() {
      return accountID_;
    }

    public static final int PRODUCTNUMBER_FIELD_NUMBER = 3;
    private int productNumber_;
    /**
     * <code>required int32 productNumber = 3;</code>
     */
    public boolean hasProductNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 productNumber = 3;</code>
     */
    public int getProductNumber() {
      return productNumber_;
    }

    public static final int PRODUCTCATEGORY_FIELD_NUMBER = 4;
    private volatile java.lang.Object productCategory_;
    /**
     * <code>required string productCategory = 4;</code>
     */
    public boolean hasProductCategory() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string productCategory = 4;</code>
     */
    public java.lang.String getProductCategory() {
      java.lang.Object ref = productCategory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productCategory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string productCategory = 4;</code>
     */
    public com.google.protobuf.ByteString
        getProductCategoryBytes() {
      java.lang.Object ref = productCategory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productCategory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 5;
    private int quantity_;
    /**
     * <code>required int32 quantity = 5;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 quantity = 5;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasRequestID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAccountID()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProductNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProductCategory()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, requestID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, accountID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, productNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, productCategory_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, quantity_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, requestID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, accountID_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, productNumber_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, productCategory_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, quantity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct)) {
        return super.equals(obj);
      }
      tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct other = (tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct) obj;

      boolean result = true;
      result = result && (hasRequestID() == other.hasRequestID());
      if (hasRequestID()) {
        result = result && (getRequestID()
            == other.getRequestID());
      }
      result = result && (hasAccountID() == other.hasAccountID());
      if (hasAccountID()) {
        result = result && (getAccountID()
            == other.getAccountID());
      }
      result = result && (hasProductNumber() == other.hasProductNumber());
      if (hasProductNumber()) {
        result = result && (getProductNumber()
            == other.getProductNumber());
      }
      result = result && (hasProductCategory() == other.hasProductCategory());
      if (hasProductCategory()) {
        result = result && getProductCategory()
            .equals(other.getProductCategory());
      }
      result = result && (hasQuantity() == other.hasQuantity());
      if (hasQuantity()) {
        result = result && (getQuantity()
            == other.getQuantity());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestID()) {
        hash = (37 * hash) + REQUESTID_FIELD_NUMBER;
        hash = (53 * hash) + getRequestID();
      }
      if (hasAccountID()) {
        hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
        hash = (53 * hash) + getAccountID();
      }
      if (hasProductNumber()) {
        hash = (37 * hash) + PRODUCTNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getProductNumber();
      }
      if (hasProductCategory()) {
        hash = (37 * hash) + PRODUCTCATEGORY_FIELD_NUMBER;
        hash = (53 * hash) + getProductCategory().hashCode();
      }
      if (hasQuantity()) {
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tejas.cloud.assignment1.proto.GetProduct}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tejas.cloud.assignment1.proto.GetProduct)
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProductOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.class, tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.Builder.class);
      }

      // Construct using tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        requestID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        accountID_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        productNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        productCategory_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct getDefaultInstanceForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.getDefaultInstance();
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct build() {
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct buildPartial() {
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct result = new tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestID_ = requestID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.accountID_ = accountID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.productNumber_ = productNumber_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.productCategory_ = productCategory_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.quantity_ = quantity_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct) {
          return mergeFrom((tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct other) {
        if (other == tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct.getDefaultInstance()) return this;
        if (other.hasRequestID()) {
          setRequestID(other.getRequestID());
        }
        if (other.hasAccountID()) {
          setAccountID(other.getAccountID());
        }
        if (other.hasProductNumber()) {
          setProductNumber(other.getProductNumber());
        }
        if (other.hasProductCategory()) {
          bitField0_ |= 0x00000008;
          productCategory_ = other.productCategory_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRequestID()) {
          return false;
        }
        if (!hasAccountID()) {
          return false;
        }
        if (!hasProductNumber()) {
          return false;
        }
        if (!hasProductCategory()) {
          return false;
        }
        if (!hasQuantity()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int requestID_ ;
      /**
       * <code>required int32 requestID = 1;</code>
       */
      public boolean hasRequestID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 requestID = 1;</code>
       */
      public int getRequestID() {
        return requestID_;
      }
      /**
       * <code>required int32 requestID = 1;</code>
       */
      public Builder setRequestID(int value) {
        bitField0_ |= 0x00000001;
        requestID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 requestID = 1;</code>
       */
      public Builder clearRequestID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestID_ = 0;
        onChanged();
        return this;
      }

      private int accountID_ ;
      /**
       * <code>required int32 accountID = 2;</code>
       */
      public boolean hasAccountID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 accountID = 2;</code>
       */
      public int getAccountID() {
        return accountID_;
      }
      /**
       * <code>required int32 accountID = 2;</code>
       */
      public Builder setAccountID(int value) {
        bitField0_ |= 0x00000002;
        accountID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 accountID = 2;</code>
       */
      public Builder clearAccountID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        accountID_ = 0;
        onChanged();
        return this;
      }

      private int productNumber_ ;
      /**
       * <code>required int32 productNumber = 3;</code>
       */
      public boolean hasProductNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 productNumber = 3;</code>
       */
      public int getProductNumber() {
        return productNumber_;
      }
      /**
       * <code>required int32 productNumber = 3;</code>
       */
      public Builder setProductNumber(int value) {
        bitField0_ |= 0x00000004;
        productNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 productNumber = 3;</code>
       */
      public Builder clearProductNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        productNumber_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object productCategory_ = "";
      /**
       * <code>required string productCategory = 4;</code>
       */
      public boolean hasProductCategory() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string productCategory = 4;</code>
       */
      public java.lang.String getProductCategory() {
        java.lang.Object ref = productCategory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productCategory_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string productCategory = 4;</code>
       */
      public com.google.protobuf.ByteString
          getProductCategoryBytes() {
        java.lang.Object ref = productCategory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productCategory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string productCategory = 4;</code>
       */
      public Builder setProductCategory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        productCategory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string productCategory = 4;</code>
       */
      public Builder clearProductCategory() {
        bitField0_ = (bitField0_ & ~0x00000008);
        productCategory_ = getDefaultInstance().getProductCategory();
        onChanged();
        return this;
      }
      /**
       * <code>required string productCategory = 4;</code>
       */
      public Builder setProductCategoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        productCategory_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>required int32 quantity = 5;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 quantity = 5;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>required int32 quantity = 5;</code>
       */
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000010;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quantity = 5;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        quantity_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tejas.cloud.assignment1.proto.GetProduct)
    }

    // @@protoc_insertion_point(class_scope:tejas.cloud.assignment1.proto.GetProduct)
    private static final tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct();
    }

    public static tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GetProduct>
        PARSER = new com.google.protobuf.AbstractParser<GetProduct>() {
      public GetProduct parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetProduct(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetProduct> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetProduct> getParserForType() {
      return PARSER;
    }

    public tejas.cloud.assignment1.proto.ProductsProtoc.GetProduct getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductSuccessOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tejas.cloud.assignment1.proto.ProductSuccess)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 unitPrice = 2;</code>
     */
    boolean hasUnitPrice();
    /**
     * <code>required int32 unitPrice = 2;</code>
     */
    int getUnitPrice();

    /**
     * <code>required int32 priceValidationPeriod = 3;</code>
     */
    boolean hasPriceValidationPeriod();
    /**
     * <code>required int32 priceValidationPeriod = 3;</code>
     */
    int getPriceValidationPeriod();
  }
  /**
   * Protobuf type {@code tejas.cloud.assignment1.proto.ProductSuccess}
   */
  public  static final class ProductSuccess extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tejas.cloud.assignment1.proto.ProductSuccess)
      ProductSuccessOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductSuccess.newBuilder() to construct.
    private ProductSuccess(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductSuccess() {
      unitPrice_ = 0;
      priceValidationPeriod_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductSuccess(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 16: {
              bitField0_ |= 0x00000001;
              unitPrice_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              priceValidationPeriod_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.class, tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.Builder.class);
    }

    private int bitField0_;
    public static final int UNITPRICE_FIELD_NUMBER = 2;
    private int unitPrice_;
    /**
     * <code>required int32 unitPrice = 2;</code>
     */
    public boolean hasUnitPrice() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 unitPrice = 2;</code>
     */
    public int getUnitPrice() {
      return unitPrice_;
    }

    public static final int PRICEVALIDATIONPERIOD_FIELD_NUMBER = 3;
    private int priceValidationPeriod_;
    /**
     * <code>required int32 priceValidationPeriod = 3;</code>
     */
    public boolean hasPriceValidationPeriod() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 priceValidationPeriod = 3;</code>
     */
    public int getPriceValidationPeriod() {
      return priceValidationPeriod_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnitPrice()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriceValidationPeriod()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, unitPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(3, priceValidationPeriod_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, unitPrice_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, priceValidationPeriod_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess)) {
        return super.equals(obj);
      }
      tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess other = (tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess) obj;

      boolean result = true;
      result = result && (hasUnitPrice() == other.hasUnitPrice());
      if (hasUnitPrice()) {
        result = result && (getUnitPrice()
            == other.getUnitPrice());
      }
      result = result && (hasPriceValidationPeriod() == other.hasPriceValidationPeriod());
      if (hasPriceValidationPeriod()) {
        result = result && (getPriceValidationPeriod()
            == other.getPriceValidationPeriod());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnitPrice()) {
        hash = (37 * hash) + UNITPRICE_FIELD_NUMBER;
        hash = (53 * hash) + getUnitPrice();
      }
      if (hasPriceValidationPeriod()) {
        hash = (37 * hash) + PRICEVALIDATIONPERIOD_FIELD_NUMBER;
        hash = (53 * hash) + getPriceValidationPeriod();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tejas.cloud.assignment1.proto.ProductSuccess}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tejas.cloud.assignment1.proto.ProductSuccess)
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.class, tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.Builder.class);
      }

      // Construct using tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        unitPrice_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        priceValidationPeriod_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess getDefaultInstanceForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.getDefaultInstance();
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess build() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess buildPartial() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess result = new tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unitPrice_ = unitPrice_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.priceValidationPeriod_ = priceValidationPeriod_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess) {
          return mergeFrom((tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess other) {
        if (other == tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess.getDefaultInstance()) return this;
        if (other.hasUnitPrice()) {
          setUnitPrice(other.getUnitPrice());
        }
        if (other.hasPriceValidationPeriod()) {
          setPriceValidationPeriod(other.getPriceValidationPeriod());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnitPrice()) {
          return false;
        }
        if (!hasPriceValidationPeriod()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int unitPrice_ ;
      /**
       * <code>required int32 unitPrice = 2;</code>
       */
      public boolean hasUnitPrice() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 unitPrice = 2;</code>
       */
      public int getUnitPrice() {
        return unitPrice_;
      }
      /**
       * <code>required int32 unitPrice = 2;</code>
       */
      public Builder setUnitPrice(int value) {
        bitField0_ |= 0x00000001;
        unitPrice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 unitPrice = 2;</code>
       */
      public Builder clearUnitPrice() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unitPrice_ = 0;
        onChanged();
        return this;
      }

      private int priceValidationPeriod_ ;
      /**
       * <code>required int32 priceValidationPeriod = 3;</code>
       */
      public boolean hasPriceValidationPeriod() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 priceValidationPeriod = 3;</code>
       */
      public int getPriceValidationPeriod() {
        return priceValidationPeriod_;
      }
      /**
       * <code>required int32 priceValidationPeriod = 3;</code>
       */
      public Builder setPriceValidationPeriod(int value) {
        bitField0_ |= 0x00000002;
        priceValidationPeriod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 priceValidationPeriod = 3;</code>
       */
      public Builder clearPriceValidationPeriod() {
        bitField0_ = (bitField0_ & ~0x00000002);
        priceValidationPeriod_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tejas.cloud.assignment1.proto.ProductSuccess)
    }

    // @@protoc_insertion_point(class_scope:tejas.cloud.assignment1.proto.ProductSuccess)
    private static final tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess();
    }

    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProductSuccess>
        PARSER = new com.google.protobuf.AbstractParser<ProductSuccess>() {
      public ProductSuccess parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProductSuccess(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductSuccess> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductSuccess> getParserForType() {
      return PARSER;
    }

    public tejas.cloud.assignment1.proto.ProductsProtoc.ProductSuccess getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProductErrorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:tejas.cloud.assignment1.proto.ProductError)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bool error = 1;</code>
     */
    boolean hasError();
    /**
     * <code>required bool error = 1;</code>
     */
    boolean getError();

    /**
     * <code>required string errorMessage = 2;</code>
     */
    boolean hasErrorMessage();
    /**
     * <code>required string errorMessage = 2;</code>
     */
    java.lang.String getErrorMessage();
    /**
     * <code>required string errorMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorMessageBytes();
  }
  /**
   * Protobuf type {@code tejas.cloud.assignment1.proto.ProductError}
   */
  public  static final class ProductError extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:tejas.cloud.assignment1.proto.ProductError)
      ProductErrorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProductError.newBuilder() to construct.
    private ProductError(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProductError() {
      error_ = false;
      errorMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProductError(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              error_ = input.readBool();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              errorMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.class, tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.Builder.class);
    }

    private int bitField0_;
    public static final int ERROR_FIELD_NUMBER = 1;
    private boolean error_;
    /**
     * <code>required bool error = 1;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool error = 1;</code>
     */
    public boolean getError() {
      return error_;
    }

    public static final int ERRORMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorMessage_;
    /**
     * <code>required string errorMessage = 2;</code>
     */
    public boolean hasErrorMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string errorMessage = 2;</code>
     */
    public java.lang.String getErrorMessage() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          errorMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string errorMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorMessageBytes() {
      java.lang.Object ref = errorMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasError()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasErrorMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, errorMessage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, error_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, errorMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof tejas.cloud.assignment1.proto.ProductsProtoc.ProductError)) {
        return super.equals(obj);
      }
      tejas.cloud.assignment1.proto.ProductsProtoc.ProductError other = (tejas.cloud.assignment1.proto.ProductsProtoc.ProductError) obj;

      boolean result = true;
      result = result && (hasError() == other.hasError());
      if (hasError()) {
        result = result && (getError()
            == other.getError());
      }
      result = result && (hasErrorMessage() == other.hasErrorMessage());
      if (hasErrorMessage()) {
        result = result && getErrorMessage()
            .equals(other.getErrorMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasError()) {
        hash = (37 * hash) + ERROR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getError());
      }
      if (hasErrorMessage()) {
        hash = (37 * hash) + ERRORMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getErrorMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(tejas.cloud.assignment1.proto.ProductsProtoc.ProductError prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code tejas.cloud.assignment1.proto.ProductError}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:tejas.cloud.assignment1.proto.ProductError)
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductErrorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.class, tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.Builder.class);
      }

      // Construct using tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        error_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        errorMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError getDefaultInstanceForType() {
        return tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.getDefaultInstance();
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError build() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductError result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError buildPartial() {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductError result = new tejas.cloud.assignment1.proto.ProductsProtoc.ProductError(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.errorMessage_ = errorMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof tejas.cloud.assignment1.proto.ProductsProtoc.ProductError) {
          return mergeFrom((tejas.cloud.assignment1.proto.ProductsProtoc.ProductError)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(tejas.cloud.assignment1.proto.ProductsProtoc.ProductError other) {
        if (other == tejas.cloud.assignment1.proto.ProductsProtoc.ProductError.getDefaultInstance()) return this;
        if (other.hasError()) {
          setError(other.getError());
        }
        if (other.hasErrorMessage()) {
          bitField0_ |= 0x00000002;
          errorMessage_ = other.errorMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasError()) {
          return false;
        }
        if (!hasErrorMessage()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        tejas.cloud.assignment1.proto.ProductsProtoc.ProductError parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (tejas.cloud.assignment1.proto.ProductsProtoc.ProductError) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private boolean error_ ;
      /**
       * <code>required bool error = 1;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool error = 1;</code>
       */
      public boolean getError() {
        return error_;
      }
      /**
       * <code>required bool error = 1;</code>
       */
      public Builder setError(boolean value) {
        bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool error = 1;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object errorMessage_ = "";
      /**
       * <code>required string errorMessage = 2;</code>
       */
      public boolean hasErrorMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string errorMessage = 2;</code>
       */
      public java.lang.String getErrorMessage() {
        java.lang.Object ref = errorMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            errorMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string errorMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorMessageBytes() {
        java.lang.Object ref = errorMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string errorMessage = 2;</code>
       */
      public Builder setErrorMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string errorMessage = 2;</code>
       */
      public Builder clearErrorMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        errorMessage_ = getDefaultInstance().getErrorMessage();
        onChanged();
        return this;
      }
      /**
       * <code>required string errorMessage = 2;</code>
       */
      public Builder setErrorMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        errorMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:tejas.cloud.assignment1.proto.ProductError)
    }

    // @@protoc_insertion_point(class_scope:tejas.cloud.assignment1.proto.ProductError)
    private static final tejas.cloud.assignment1.proto.ProductsProtoc.ProductError DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new tejas.cloud.assignment1.proto.ProductsProtoc.ProductError();
    }

    public static tejas.cloud.assignment1.proto.ProductsProtoc.ProductError getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProductError>
        PARSER = new com.google.protobuf.AbstractParser<ProductError>() {
      public ProductError parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProductError(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProductError> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProductError> getParserForType() {
      return PARSER;
    }

    public tejas.cloud.assignment1.proto.ProductsProtoc.ProductError getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protobuf.proto\022\035tejas.cloud.assignment" +
      "1.proto\"t\n\nGetProduct\022\021\n\trequestID\030\001 \002(\005" +
      "\022\021\n\taccountID\030\002 \002(\005\022\025\n\rproductNumber\030\003 \002" +
      "(\005\022\027\n\017productCategory\030\004 \002(\t\022\020\n\010quantity\030" +
      "\005 \002(\005\"B\n\016ProductSuccess\022\021\n\tunitPrice\030\002 \002" +
      "(\005\022\035\n\025priceValidationPeriod\030\003 \002(\005\"3\n\014Pro" +
      "ductError\022\r\n\005error\030\001 \002(\010\022\024\n\014errorMessage" +
      "\030\002 \002(\tB/\n\035tejas.cloud.assignment1.protoB" +
      "\016ProductsProtoc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tejas_cloud_assignment1_proto_GetProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tejas_cloud_assignment1_proto_GetProduct_descriptor,
        new java.lang.String[] { "RequestID", "AccountID", "ProductNumber", "ProductCategory", "Quantity", });
    internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tejas_cloud_assignment1_proto_ProductSuccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tejas_cloud_assignment1_proto_ProductSuccess_descriptor,
        new java.lang.String[] { "UnitPrice", "PriceValidationPeriod", });
    internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tejas_cloud_assignment1_proto_ProductError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tejas_cloud_assignment1_proto_ProductError_descriptor,
        new java.lang.String[] { "Error", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
